& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'Label1.Name' = 'Label1'
'RTB_InstallParameter.Name' = 'RTB_InstallParameter'
'TextBox3.Name' = 'TextBox3'
'TextBox2.Name' = 'TextBox2'
'Label5.Name' = 'Label5'
'Label2.Name' = 'Label2'
'TB_KillProcessName.Name' = 'TB_KillProcessName'
'Label3.Name' = 'Label3'
'TB_InstallFile.Name' = 'TB_InstallFile'
'TextBox1.Name' = 'TextBox1'
'$this.Name' = 'Form1'
'R_System.Name' = 'R_System'
'RichTextBox1.Name' = 'RichTextBox1'
'R_User.Name' = 'R_User'
'Label4.Name' = 'Label4'
'RadioButton2.Name' = 'RadioButton2'
'Label8.Name' = 'Label8'
'TB_PackageName.Name' = 'TB_PackageName'
'Label9.Name' = 'Label9'
'B_create_Intunewin.Name' = 'B_create_Intunewin'
'Label7.Name' = 'Label7'
'Button1.Name' = 'Button1'
'Label6.Name' = 'Label6'
'RadioButton1.Name' = 'RadioButton1'
'Button2.Name' = 'Button2'
'GroupBox1.Name' = 'GroupBox1'
}
}